#pragma once

// ============================================================
// Generated by LVGL Studio — drop into your Arduino / ESP-IDF
// project. Call build_dashboard(lv_scr_act()) after lv_init().
// ============================================================

#include "lvgl.h"
#include <stdio.h>
#include <math.h>
#include "esp_timer.h"

// Data-bound widgets (set these via update_dashboard())
static lv_obj_t *ui_fuel = NULL;
static lv_obj_t *ui_engineTemp = NULL;
static lv_obj_t *ui_speed = NULL;
static lv_obj_t *ui_speedLimit = NULL;
static lv_obj_t *ui_proximity = NULL;
static lv_obj_t *ui_proximityArc = NULL;
static lv_obj_t *ui_proximityIn = NULL;
static lv_obj_t *ui_odometer = NULL;
static lv_obj_t *ui_avgSpeed = NULL;
static lv_obj_t *ui_avgFuel = NULL;
static lv_obj_t *ui_speed_2 = NULL;
static lv_obj_t *ui_gearP = NULL;
static lv_obj_t *ui_gearR = NULL;
static lv_obj_t *ui_gearN = NULL;
static lv_obj_t *ui_gearD = NULL;
static lv_obj_t *ui_turnLeft = NULL;
static lv_obj_t *ui_turnRight = NULL;
static lv_obj_t *ui_headLamp = NULL;
static lv_obj_t *ui_brakeLamp = NULL;
static lv_obj_t *ui_link = NULL;

void build_dashboard(lv_obj_t *scr) {
  lv_obj_set_style_bg_color(scr, lv_color_hex(0x16181C), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_pad_all(scr, 0, LV_PART_MAIN);
  lv_obj_clear_flag(scr, LV_OBJ_FLAG_SCROLLABLE);

  // ---- label  ----
  lv_obj_t *w0 = lv_label_create(scr);
  lv_label_set_text(w0, "19:30");
  lv_obj_set_size(w0, 120, 32);
  lv_obj_set_style_text_color(w0, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(w0, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w0, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w0, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w0, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w0, 28, 18);

  // ---- label  ----
  lv_obj_t *w1 = lv_label_create(scr);
  lv_label_set_text(w1, "SUBARU  WRX  2006");
  lv_obj_set_size(w1, 220, 22);
  lv_obj_set_style_text_color(w1, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w1, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w1, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w1, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w1, 408, 22);

  // ---- label  ----
  lv_obj_t *w2 = lv_label_create(scr);
  lv_label_set_text(w2, "04 / 21 / 26");
  lv_obj_set_size(w2, 170, 32);
  lv_obj_set_style_text_color(w2, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(w2, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w2, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w2, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w2, 830, 18);

  // ---- rect  ----
  lv_obj_t *w3 = lv_obj_create(scr);
  lv_obj_set_size(w3, 968, 1);
  lv_obj_set_pos(w3, 28, 58);
  lv_obj_set_style_radius(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w3, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w3, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w3, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w3, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w3, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w3, LV_OBJ_FLAG_SCROLLABLE);

  // ---- indicator [turnLeft] ----
  ui_turnLeft = lv_label_create(scr);
  lv_label_set_text(ui_turnLeft, LV_SYMBOL_LEFT);
  lv_obj_set_size(ui_turnLeft, 24, 24);
  lv_obj_set_style_text_color(ui_turnLeft, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_turnLeft, LV_FONT_DEFAULT, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_turnLeft, 255, LV_PART_MAIN);
  lv_obj_set_pos(ui_turnLeft, 350, 70);

  // ---- indicator [headLamp] ----
  ui_headLamp = lv_label_create(scr);
  lv_label_set_text(ui_headLamp, LV_SYMBOL_EYE_OPEN);
  lv_obj_set_size(ui_headLamp, 24, 24);
  lv_obj_set_style_text_color(ui_headLamp, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_headLamp, LV_FONT_DEFAULT, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_headLamp, 255, LV_PART_MAIN);
  lv_obj_set_pos(ui_headLamp, 466, 70);

  // ---- indicator [brakeLamp] ----
  ui_brakeLamp = lv_label_create(scr);
  lv_label_set_text(ui_brakeLamp, LV_SYMBOL_WARNING);
  lv_obj_set_size(ui_brakeLamp, 24, 24);
  lv_obj_set_style_text_color(ui_brakeLamp, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_brakeLamp, LV_FONT_DEFAULT, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_brakeLamp, 255, LV_PART_MAIN);
  lv_obj_set_pos(ui_brakeLamp, 582, 70);

  // ---- indicator [turnRight] ----
  ui_turnRight = lv_label_create(scr);
  lv_label_set_text(ui_turnRight, LV_SYMBOL_RIGHT);
  lv_obj_set_size(ui_turnRight, 24, 24);
  lv_obj_set_style_text_color(ui_turnRight, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_turnRight, LV_FONT_DEFAULT, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_turnRight, 255, LV_PART_MAIN);
  lv_obj_set_pos(ui_turnRight, 698, 70);

  // ---- link status [link] ----
  ui_link = lv_label_create(scr);
  lv_label_set_text(ui_link, "LINK");
  lv_obj_set_size(ui_link, 80, 24);
  lv_obj_set_style_text_color(ui_link, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_link, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_link, 255, LV_PART_MAIN);
  lv_obj_set_pos(ui_link, 900, 70);

  // ---- label [fuel] ----
  ui_fuel = lv_label_create(scr);
  lv_label_set_text(ui_fuel, "86");
  lv_obj_set_size(ui_fuel, 140, 80);
  lv_obj_set_style_text_color(ui_fuel, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_fuel, &lv_font_montserrat_48, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_fuel, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_fuel, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_fuel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_fuel, 36, 110);

  // ---- label  ----
  lv_obj_t *w5 = lv_label_create(scr);
  lv_label_set_text(w5, "%");
  lv_obj_set_size(w5, 40, 50);
  lv_obj_set_style_text_color(w5, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w5, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w5, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w5, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w5, 176, 128);

  // ---- label  ----
  lv_obj_t *w6 = lv_label_create(scr);
  lv_label_set_text(w6, "FUEL LEVEL");
  lv_obj_set_size(w6, 200, 22);
  lv_obj_set_style_text_color(w6, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w6, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w6, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w6, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w6, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w6, 40, 200);

  // ---- rect  ----
  lv_obj_t *w7 = lv_obj_create(scr);
  lv_obj_set_size(w7, 14, 30);
  lv_obj_set_pos(w7, 40, 240);
  lv_obj_set_style_radius(w7, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w7, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w7, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w7, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w7, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w7, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w7, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w7, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w7, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w7, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w7, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w8 = lv_obj_create(scr);
  lv_obj_set_size(w8, 14, 30);
  lv_obj_set_pos(w8, 62, 240);
  lv_obj_set_style_radius(w8, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w8, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w8, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w8, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w8, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w8, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w8, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w8, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w8, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w8, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w8, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w9 = lv_obj_create(scr);
  lv_obj_set_size(w9, 14, 30);
  lv_obj_set_pos(w9, 84, 240);
  lv_obj_set_style_radius(w9, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w9, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w9, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w9, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w9, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w9, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w9, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w9, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w9, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w9, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w9, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w10 = lv_obj_create(scr);
  lv_obj_set_size(w10, 14, 30);
  lv_obj_set_pos(w10, 106, 240);
  lv_obj_set_style_radius(w10, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w10, lv_color_hex(0x00E5DD), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w10, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w10, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w10, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w10, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w10, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w10, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w10, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w10, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w10, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w11 = lv_obj_create(scr);
  lv_obj_set_size(w11, 14, 30);
  lv_obj_set_pos(w11, 128, 240);
  lv_obj_set_style_radius(w11, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w11, lv_color_hex(0x00E5DD), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w11, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w11, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w11, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w11, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w11, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w11, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w11, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w11, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w11, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w12 = lv_obj_create(scr);
  lv_obj_set_size(w12, 14, 30);
  lv_obj_set_pos(w12, 150, 240);
  lv_obj_set_style_radius(w12, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w12, lv_color_hex(0x00E5DD), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w12, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w12, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w12, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w12, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w12, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w12, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w12, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w12, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w12, LV_OBJ_FLAG_SCROLLABLE);

  // ---- rect  ----
  lv_obj_t *w13 = lv_obj_create(scr);
  lv_obj_set_size(w13, 14, 30);
  lv_obj_set_pos(w13, 172, 240);
  lv_obj_set_style_radius(w13, 3, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w13, lv_color_hex(0x00E5DD), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w13, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w13, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w13, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w13, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w13, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w13, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w13, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w13, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w13, LV_OBJ_FLAG_SCROLLABLE);

  // ---- label  ----
  lv_obj_t *w14 = lv_label_create(scr);
  lv_label_set_text(w14, "ECO");
  lv_obj_set_size(w14, 60, 22);
  lv_obj_set_style_text_color(w14, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_text_font(w14, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w14, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w14, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w14, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w14, 40, 300);

  // ---- label  ----
  lv_obj_t *w15 = lv_label_create(scr);
  lv_label_set_text(w15, "MODE");
  lv_obj_set_size(w15, 100, 22);
  lv_obj_set_style_text_color(w15, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(w15, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w15, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w15, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w15, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w15, 92, 300);

  // ---- label [engineTemp] ----
  ui_engineTemp = lv_label_create(scr);
  lv_label_set_text(ui_engineTemp, "195");
  lv_obj_set_size(ui_engineTemp, 140, 50);
  lv_obj_set_style_text_color(ui_engineTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_engineTemp, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_engineTemp, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_engineTemp, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_engineTemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_engineTemp, 40, 340);

  // ---- label  ----
  lv_obj_t *w17 = lv_label_create(scr);
  lv_label_set_text(w17, "°F");
  lv_obj_set_size(w17, 20, 32);
  lv_obj_set_style_text_color(w17, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w17, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w17, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w17, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w17, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w17, 180, 360);

  // ---- label [speed] ----
  ui_speed = lv_label_create(scr);
  lv_label_set_text(ui_speed, "68");
  lv_obj_set_size(ui_speed, 160, 100);
  lv_obj_set_style_text_color(ui_speed, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_speed, &lv_font_montserrat_48, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_speed, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_speed, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_speed, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_speed, 440, 90);

  // ---- label  ----
  lv_obj_t *w19 = lv_label_create(scr);
  lv_label_set_text(w19, "MPH");
  lv_obj_set_size(w19, 80, 32);
  lv_obj_set_style_text_color(w19, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_text_font(w19, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w19, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w19, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w19, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w19, 480, 220);

  // ---- circle  ----
  lv_obj_t *w20 = lv_obj_create(scr);
  lv_obj_set_size(w20, 90, 90);
  lv_obj_set_pos(w20, 467, 260);
  lv_obj_set_style_radius(w20, 45, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w20, lv_color_hex(0xF0F0F0), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w20, 255, LV_PART_MAIN);
  lv_obj_set_style_border_color(w20, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_border_width(w20, 5, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w20, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w20, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w20, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w20, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w20, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w20, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w20, LV_OBJ_FLAG_SCROLLABLE);

  // ---- label [speedLimit] ----
  ui_speedLimit = lv_label_create(scr);
  lv_label_set_text(ui_speedLimit, "70");
  lv_obj_set_size(ui_speedLimit, 60, 50);
  lv_obj_set_style_text_color(ui_speedLimit, lv_color_hex(0x0A6FCC), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_speedLimit, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_speedLimit, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_speedLimit, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_speedLimit, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_speedLimit, 485, 282);

  // ---- label  ----
  lv_obj_t *w22 = lv_label_create(scr);
  lv_label_set_text(w22, LV_SYMBOL_WARNING);
  lv_obj_set_size(w22, 24, 24);
  lv_obj_set_style_text_color(w22, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_text_font(w22, LV_FONT_DEFAULT, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w22, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w22, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w22, 428, 378);

  // ---- bar [proximity] ----
  ui_proximity = lv_bar_create(scr);
  lv_obj_set_size(ui_proximity, 1, 1);
  lv_obj_set_pos(ui_proximity, 0, 0);
  lv_bar_set_range(ui_proximity, 0, 100);
  lv_bar_set_value(ui_proximity, 70, LV_ANIM_OFF);
  lv_obj_set_style_bg_color(ui_proximity, lv_color_hex(0x2A2224), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(ui_proximity, 255, LV_PART_MAIN);
  lv_obj_set_style_radius(ui_proximity, 4, LV_PART_MAIN);
  lv_obj_set_style_bg_color(ui_proximity, lv_color_hex(0xE8453C), LV_PART_INDICATOR);
  lv_obj_set_style_bg_opa(ui_proximity, 255, LV_PART_INDICATOR);
  lv_obj_set_style_radius(ui_proximity, 4, LV_PART_INDICATOR);
  lv_obj_set_style_border_width(ui_proximity, 0, LV_PART_MAIN);

  // ---- arc [proximityArc] ----
  ui_proximityArc = lv_arc_create(scr);
  lv_obj_set_size(ui_proximityArc, 156, 156);
  lv_obj_set_pos(ui_proximityArc, 434, 228);
  lv_arc_set_range(ui_proximityArc, 0, 100);
  lv_arc_set_bg_angles(ui_proximityArc, 135, 45);
  lv_arc_set_rotation(ui_proximityArc, 0);
  lv_arc_set_value(ui_proximityArc, 70);
  lv_obj_set_style_arc_width(ui_proximityArc, 8, LV_PART_MAIN);
  lv_obj_set_style_arc_color(ui_proximityArc, lv_color_hex(0x2A2224), LV_PART_MAIN);
  lv_obj_set_style_arc_opa(ui_proximityArc, 255, LV_PART_MAIN);
  lv_obj_set_style_arc_width(ui_proximityArc, 10, LV_PART_INDICATOR);
  lv_obj_set_style_arc_color(ui_proximityArc, lv_color_hex(0xE8453C), LV_PART_INDICATOR);
  lv_obj_set_style_arc_opa(ui_proximityArc, 255, LV_PART_INDICATOR);
  lv_obj_remove_style(ui_proximityArc, NULL, LV_PART_KNOB);
  lv_obj_clear_flag(ui_proximityArc, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_clear_flag(ui_proximityArc, LV_OBJ_FLAG_SCROLLABLE);

  // ---- label [proximityIn] ----
  ui_proximityIn = lv_label_create(scr);
  lv_label_set_text(ui_proximityIn, "80 in");
  lv_obj_set_size(ui_proximityIn, 110, 28);
  lv_obj_set_style_text_color(ui_proximityIn, lv_color_hex(0xFF6B5A), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_proximityIn, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_proximityIn, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_proximityIn, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_proximityIn, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_proximityIn, 470, 388);

  // ---- label  ----
  lv_obj_t *w25 = lv_label_create(scr);
  lv_label_set_text(w25, "FRONT OBJECT");
  lv_obj_set_size(w25, 180, 22);
  lv_obj_set_style_text_color(w25, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(w25, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w25, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w25, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w25, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w25, 444, 420);

  // ---- label [odometer] ----
  ui_odometer = lv_label_create(scr);
  lv_label_set_text(ui_odometer, "14,175");
  lv_obj_set_size(ui_odometer, 140, 50);
  lv_obj_set_style_text_color(ui_odometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_odometer, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_odometer, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_odometer, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_odometer, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_odometer, 744, 100);

  // ---- label  ----
  lv_obj_t *w27 = lv_label_create(scr);
  lv_label_set_text(w27, "ODOMETER");
  lv_obj_set_size(w27, 120, 22);
  lv_obj_set_style_text_color(w27, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w27, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w27, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w27, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w27, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w27, 762, 150);

  // ---- label [avgSpeed] ----
  ui_avgSpeed = lv_label_create(scr);
  lv_label_set_text(ui_avgSpeed, "78 mph");
  lv_obj_set_size(ui_avgSpeed, 140, 50);
  lv_obj_set_style_text_color(ui_avgSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_avgSpeed, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_avgSpeed, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_avgSpeed, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_avgSpeed, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_avgSpeed, 744, 215);

  // ---- label  ----
  lv_obj_t *w29 = lv_label_create(scr);
  lv_label_set_text(w29, "AVG. SPEED");
  lv_obj_set_size(w29, 140, 22);
  lv_obj_set_style_text_color(w29, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w29, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w29, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w29, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w29, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w29, 762, 265);

  // ---- label [avgFuel] ----
  ui_avgFuel = lv_label_create(scr);
  lv_label_set_text(ui_avgFuel, "34 mpg");
  lv_obj_set_size(ui_avgFuel, 140, 50);
  lv_obj_set_style_text_color(ui_avgFuel, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_avgFuel, &lv_font_montserrat_40, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_avgFuel, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_avgFuel, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_avgFuel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_avgFuel, 744, 330);

  // ---- label  ----
  lv_obj_t *w31 = lv_label_create(scr);
  lv_label_set_text(w31, "AVG. FUEL ECONOMY");
  lv_obj_set_size(w31, 200, 22);
  lv_obj_set_style_text_color(w31, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w31, &lv_font_montserrat_16, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w31, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w31, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w31, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w31, 762, 380);

  // ---- rect  ----
  lv_obj_t *w32 = lv_obj_create(scr);
  lv_obj_set_size(w32, 968, 1);
  lv_obj_set_pos(w32, 28, 535);
  lv_obj_set_style_radius(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w32, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w32, 255, LV_PART_MAIN);
  lv_obj_set_style_border_width(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w32, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w32, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w32, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w32, LV_OBJ_FLAG_SCROLLABLE);

  // ---- circle  ----
  lv_obj_t *w33 = lv_obj_create(scr);
  lv_obj_set_size(w33, 10, 10);
  lv_obj_set_pos(w33, 40, 566);
  lv_obj_set_style_radius(w33, 5, LV_PART_MAIN);
  lv_obj_set_style_bg_color(w33, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(w33, 255, LV_PART_MAIN);
  lv_obj_set_style_border_color(w33, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_border_width(w33, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_color(w33, lv_color_hex(0x000000), LV_PART_MAIN);
  lv_obj_set_style_shadow_width(w33, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_x(w33, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_ofs_y(w33, 0, LV_PART_MAIN);
  lv_obj_set_style_shadow_opa(w33, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(w33, 0, LV_PART_MAIN);
  lv_obj_clear_flag(w33, LV_OBJ_FLAG_SCROLLABLE);

  // ---- label  ----
  lv_obj_t *w34 = lv_label_create(scr);
  lv_label_set_text(w34, "READY");
  lv_obj_set_size(w34, 80, 28);
  lv_obj_set_style_text_color(w34, lv_color_hex(0x34D64A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w34, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w34, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w34, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w34, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w34, 60, 558);

  // ---- label [speed] ----
  ui_speed_2 = lv_label_create(scr);
  lv_label_set_text(ui_speed_2, "78");
  lv_obj_set_size(ui_speed_2, 40, 28);
  lv_obj_set_style_text_color(ui_speed_2, lv_color_hex(0x0C91FF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_speed_2, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_speed_2, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_speed_2, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_speed_2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_speed_2, 470, 558);

  // ---- label  ----
  lv_obj_t *w36 = lv_label_create(scr);
  lv_label_set_text(w36, "mph");
  lv_obj_set_size(w36, 60, 28);
  lv_obj_set_style_text_color(w36, lv_color_hex(0x6E707A), LV_PART_MAIN);
  lv_obj_set_style_text_font(w36, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(w36, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(w36, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(w36, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(w36, 510, 558);

  // ---- label [gearP] ----
  ui_gearP = lv_label_create(scr);
  lv_label_set_text(ui_gearP, "P");
  lv_obj_set_size(ui_gearP, 24, 28);
  lv_obj_set_style_text_color(ui_gearP, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_gearP, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_gearP, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_gearP, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_gearP, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_gearP, 840, 558);

  // ---- label [gearR] ----
  ui_gearR = lv_label_create(scr);
  lv_label_set_text(ui_gearR, "R");
  lv_obj_set_size(ui_gearR, 24, 28);
  lv_obj_set_style_text_color(ui_gearR, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_gearR, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_gearR, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_gearR, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_gearR, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_gearR, 880, 558);

  // ---- label [gearN] ----
  ui_gearN = lv_label_create(scr);
  lv_label_set_text(ui_gearN, "N");
  lv_obj_set_size(ui_gearN, 24, 28);
  lv_obj_set_style_text_color(ui_gearN, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_gearN, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_gearN, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_gearN, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_gearN, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_gearN, 920, 558);

  // ---- label [gearD] ----
  ui_gearD = lv_label_create(scr);
  lv_label_set_text(ui_gearD, "D");
  lv_obj_set_size(ui_gearD, 24, 28);
  lv_obj_set_style_text_color(ui_gearD, lv_color_hex(0x4A4C55), LV_PART_MAIN);
  lv_obj_set_style_text_font(ui_gearD, &lv_font_montserrat_22, LV_PART_MAIN);
  lv_obj_set_style_text_opa(ui_gearD, 255, LV_PART_MAIN);
  lv_obj_set_style_text_letter_space(ui_gearD, 0, LV_PART_MAIN);
  lv_obj_set_style_text_align(ui_gearD, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN);
  lv_obj_set_pos(ui_gearD, 960, 558);

}

// ------------------------------------------------------------
// Example: call from your data pipeline to update live values.
// ------------------------------------------------------------
void set_fuel_text(const char *s) { if (ui_fuel) lv_label_set_text(ui_fuel, s); }
void set_engineTemp_text(const char *s) { if (ui_engineTemp) lv_label_set_text(ui_engineTemp, s); }
void set_speed_text(const char *s) { if (ui_speed) lv_label_set_text(ui_speed, s); if (ui_speed_2) lv_label_set_text(ui_speed_2, s); }
void set_speedLimit_text(const char *s) { if (ui_speedLimit) lv_label_set_text(ui_speedLimit, s); }
void set_proximity_value(int v) { if (ui_proximity) lv_bar_set_value(ui_proximity, v, LV_ANIM_ON); if (ui_proximityArc) lv_arc_set_value(ui_proximityArc, v); }
void set_proximityIn_text(const char *s) { if (ui_proximityIn) lv_label_set_text(ui_proximityIn, s); }
void set_odometer_text(const char *s) { if (ui_odometer) lv_label_set_text(ui_odometer, s); }
void set_avgSpeed_text(const char *s) { if (ui_avgSpeed) lv_label_set_text(ui_avgSpeed, s); }
void set_avgFuel_text(const char *s) { if (ui_avgFuel) lv_label_set_text(ui_avgFuel, s); }
void set_gearP_text(const char *s) { if (ui_gearP) lv_label_set_text(ui_gearP, s); }
void set_gearR_text(const char *s) { if (ui_gearR) lv_label_set_text(ui_gearR, s); }
void set_gearN_text(const char *s) { if (ui_gearN) lv_label_set_text(ui_gearN, s); }
void set_gearD_text(const char *s) { if (ui_gearD) lv_label_set_text(ui_gearD, s); }
void set_turn_left_on(bool on) { if (ui_turnLeft) lv_obj_set_style_text_color(ui_turnLeft, on ? lv_color_hex(0xFFB020) : lv_color_hex(0x4A4C55), LV_PART_MAIN); }
void set_turn_right_on(bool on) { if (ui_turnRight) lv_obj_set_style_text_color(ui_turnRight, on ? lv_color_hex(0xFFB020) : lv_color_hex(0x4A4C55), LV_PART_MAIN); }
void set_head_lamp_on(bool on) { if (ui_headLamp) lv_obj_set_style_text_color(ui_headLamp, on ? lv_color_hex(0x7CC4FF) : lv_color_hex(0x4A4C55), LV_PART_MAIN); }
void set_brake_lamp_on(bool on) { if (ui_brakeLamp) lv_obj_set_style_text_color(ui_brakeLamp, on ? lv_color_hex(0xFF5560) : lv_color_hex(0x4A4C55), LV_PART_MAIN); }
void set_link_text(const char *s, bool ok) { if (ui_link) { lv_label_set_text(ui_link, s); lv_obj_set_style_text_color(ui_link, ok ? lv_color_hex(0x34D64A) : lv_color_hex(0xFF5560), LV_PART_MAIN); } }

// ------------------------------------------------------------
// Live demo: updates every bound widget so the board shows motion after flash.
// Call from loop() ~20 Hz inside lvgl_port_lock() until your real data feeds these setters.
// ------------------------------------------------------------
void studio_demo_tick(void) {
  char buf[48];
  uint32_t ms = (uint32_t)(esp_timer_get_time() / 1000ULL);
  static uint32_t t0 = 0;
  if (t0 == 0) t0 = ms;
  uint32_t t = ms - t0;
  (void)buf;

  snprintf(buf, sizeof(buf), "%d", (int)(18 + (t / 160) % 82)); set_fuel_text(buf);

  snprintf(buf, sizeof(buf), "%d °F", (int)(185 + (t / 120) % 20)); set_engineTemp_text(buf);

  snprintf(buf, sizeof(buf), "%d", (int)(25 + (t / 100) % 75)); set_speed_text(buf);

  snprintf(buf, sizeof(buf), "%d", (int)(50 + (t / 260) % 35)); set_speedLimit_text(buf);

  set_proximity_value((int)((t / 40) % 101));

  snprintf(buf, sizeof(buf), "%d in", (int)(8 + (t / 150) % 92)); set_proximityIn_text(buf);

  snprintf(buf, sizeof(buf), "%lu mi", (unsigned long)(48210u + (t % 500))); set_odometer_text(buf);

  snprintf(buf, sizeof(buf), "%d mph", (int)(35 + (t / 90) % 55)); set_avgSpeed_text(buf);

  snprintf(buf, sizeof(buf), "%d mpg", (int)(18 + (t / 100) % 35)); set_avgFuel_text(buf);

  set_gearP_text(((t / 700) % 4) == 0 ? "P" : " ");

  set_gearR_text(((t / 700) % 4) == 1 ? "R" : " ");

  set_gearN_text(((t / 700) % 4) == 2 ? "N" : " ");

  set_gearD_text(((t / 700) % 4) == 3 ? "D" : " ");

}
